# Generated by Django 5.0.7 on 2024-07-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_report_alter_product_options_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_stock',
            field=models.IntegerField(default=0, verbose_name='Начальные запасы'),
        ),
    ]
