# Generated by Django 5.0.7 on 2024-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_initial_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remaining_stock',
            field=models.IntegerField(default=0, verbose_name='Остаток на складе'),
        ),
    ]
