# Generated by Django 5.0.7 on 2024-07-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_sale_date_sale_price_sale_sale_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='purchase_price',
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
