# Generated by Django 5.0.7 on 2024-07-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_category_alter_product_initial_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена продажи'),
        ),
    ]
