# Generated by Django 5.0.7 on 2024-07-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_product_sale_price_remove_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Цена продажи'),
        ),
    ]
