# Generated by Django 5.0.7 on 2024-07-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_sale_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена покупки'),
        ),
    ]
