# Generated by Django 5.0.7 on 2024-07-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_product_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена покупки'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена продажи'),
        ),
    ]
